// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyCalendar.Infrastructure;

#nullable disable

namespace PharmacyCalendar.Infrastructure.Migrations
{
    [DbContext(typeof(PharmacyCalendarDbContext))]
    [Migration("20250316101250_InitializeDb")]
    partial class InitializeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyCalendar.Domain.AggregatesModel.TechnicalOfficerAggregate.TechniacalOfficerWorkShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TechnicalOfficerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weekdays")
                        .HasColumnType("int");

                    b.Property<int>("WorkShift")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalOfficerId");

                    b.ToTable("TechnicalOfficerWorkshift", (string)null);
                });

            modelBuilder.Entity("PharmacyCalendar.Domain.AggregatesModel.TechnicalOfficerAggregate.TechnicalOfficer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("TechnicalOfficer", (string)null);
                });

            modelBuilder.Entity("PharmacyCalendar.Domain.AggregatesModel.TechnicalOfficerAggregate.TechniacalOfficerWorkShift", b =>
                {
                    b.HasOne("PharmacyCalendar.Domain.AggregatesModel.TechnicalOfficerAggregate.TechnicalOfficer", "TechnicalOfficer")
                        .WithMany("TechniacalOfficerWorkShift")
                        .HasForeignKey("TechnicalOfficerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TechnicalOfficer");
                });

            modelBuilder.Entity("PharmacyCalendar.Domain.AggregatesModel.TechnicalOfficerAggregate.TechnicalOfficer", b =>
                {
                    b.Navigation("TechniacalOfficerWorkShift");
                });
#pragma warning restore 612, 618
        }
    }
}
